# Bluetoothの名称を固定（PC側で識別しやすくするため）
CONFIG_ZMK_KEYBOARD_NAME="K-GRID"

# Bluetoothの出力を最大にする
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# USB接続を強制的に有効化
CONFIG_ZMK_USB=y

# スリープを一時的に無効化して確実に接続を確認する
CONFIG_ZMK_SLEEP=n
