name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      # matrix などの複雑な指定をやめ、直接指定する形式に変更
      machine: seeeduino_xiao_ble
      shield: k_grid_left k_grid_right
